build-docker-master:
  image: docker:latest
  stage: build
  cache:
    untracked: true
  services:
    - docker:dind
  before_script:
    - export DOCKER_REGISTRY_USER=$MENTORING_CI_REGISTRY_USER
    - export DOCKER_REGISTRY_PASSWORD=$MENTORING_CI_REGISTRY_PASSWORD
    - export DOCKER_REGISTRY_URL=$MENTORING_CI_REGISTRY
    - export COMMIT_HASH=$CI_COMMIT_SHA
    - export IMAGE_NAME_WITH_REGISTRY_PREFIX=$MENTORING_CI_REGISTRY_IMAGE_PERFIX
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY_URL
  script:
    - echo "Building..."
    - export CONTAINER_FULL_IMAGE_NAME_WITH_TAG=$MENTORING_CI_REGISTRY_IMAGE_PERFIX/$APP_IMAGE_NAME:$COMMIT_HASH
    - docker build -f ./Dockerfile --pull -t built-image-name .
    - docker tag built-image-name "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
    - docker push "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
    - echo $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
    - echo "Deploying on CapRover..."
    - docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl $MENTORING_CAPROVER_URL --caproverPassword $MENTORING_CAPROVER_PASSWORD --caproverApp $CAPROVER_APP --imageName $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
  only:
    - master
